version: "3.7"


services:
  dots_gazebo_service:
    image: dots/rosdevel:foxy
    ports:
      - "8080:8080"
      - "8081:80"
      - "8082:5900"
      - "8085:8085"
    volumes:
      - ../:/home/dots/dots_system
    networks:
      - dots_network

    user: dots
    entrypoint: /bin/bash -c 'cd dots_system && ../start_simulator use_gzweb:=true'

  dots_controller_service:
    container_name: dots_controller
    build:
      context: ../
      dockerfile: docker/Dockerfile.controller
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: dots/controller:foxy
    networks:
      - dots_network
    command: /bin/bash start_controller robot_pose:=0,-0.5,1.3 

networks:
  dots_network: